Leader/urls.py
from . import  views
from django.conf.urls import url

app_name='Leader'

urlpatterns = [
    url(r'^create/(?P<cont_id>[0-9]+)$',views.index,name='index'),
    url(r'^(?P<cont_id>[0-9]+)$',views.leader ,name='leader'),
    url(r'(?P<uname>[0-9A-Za-z_]+)$',views.get_user,name='user'),
]

codedaemon/urls.py
from django.contrib import admin
from django.conf.urls import include,url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls')),
    url(r'^past_contest/', include('Practice.urls')),
    url(r'^reverse/', include('Reverse.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^discussion/', include('discussion.urls')),
    url(r'^Compile_run/', include('Compile_run.urls')),
    url(r'^Leader/', include('Leader.urls')),
    url(r'^adminpanel/',include('adminpanel.urls')),
]

discussion/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from . import views

app_name='discussion'
urlpatterns = [
    url(r'^(?P<contest_id>[0-9]+)/$', views.disc,name='disc'), 
    url(r'^addcom/$',views.addcom,name='addcom'), 
    url(r'^delcom/$', views.delcom,name='delcom'), 
]


home/urls.py
from django.conf.urls import url,include
from . import views
app_name='home'
urlpatterns = [
    url(r'^$',views.contest,name='contest'),
    url(r'^(?P<contest_id>[0-9]+)/contest_details/$',views.contest_details,name='contest_details'),
    url(r'^(?P<contest_id>[0-9]+)/contest_info/$',views.contest_info,name='contest_info'),
    #url(r'^problem/(?P<problem_id>[0-9]+)/$',views.problem,name='problem'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^onsearch/$',views.onsearch,name='onsearch'),
    url(r'^profile/$',views.profile,name='profile'),
    url(r'^profileupdate/$',views.profileUpdate,name='profileUpdate'),
    url(r'^(?P<contest_id>[0-9]+)/contest_signup/$',views.contest_signup,name='contest_signup'),
    url(r'^contact_us/$',views.contactPage,name='contactPage'),
    url(r'^contact/$',views.contact,name='contact'),
]

discussion/models.py
from django.db import models
from login.models import User
from home.models import Contest


class Discussion(models.Model):
	message=models.TextField(max_length=250)
	time=models.DateTimeField()
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	contest=models.ForeignKey(Contest,on_delete=models.CASCADE)

	def __str__(self):
		return 'User : '+self.user.username + ' - Time : '+ str(self.time) + ' Message : ' + self.message 



discussion/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from login.models import User
from home.models import Contest,Problem
import datetime
from .models import Discussion
from login.models import User
from django.apps import apps

from channels import Group
from home.views import get_u


def get_rank(user,contest_id):
	cont=apps.get_model(app_label='Leader', model_name="cont_"+str(contest_id))
	me = cont.objects.get(user=User.objects.get(id=user))
	all_users  = cont.objects.all()
	for rank,u in enumerate(all_users):
		if u == me:
			return rank+1

def disc(request,contest_id):
	contest=Contest.objects.get(id=contest_id)
	user=get_object_or_404(User,username=get_u(request))
	return render(request,'discussion/forum.html',{'All':Discussion.objects.filter(contest=contest).order_by('-id'),'contest_id':contest_id,'contest':contest,'end':str(contest.end_time)[:16:],'Rank':get_rank(user.id,contest.id)})


def addcom(request):
	user=User.objects.filter(username=get_u(request)).first()
	con = request.POST.get('con')
	contest=Contest.objects.get(id=con)
	message = request.POST.get('comment')
	
	time = datetime.datetime.now().replace(microsecond=0)
	
	discussion = Discussion(user=user,contest=contest,message=message,time=time)
	discussion.save()
	con_name=contest.con_name.replace(" ","_")
    
	Group(con_name).send({'text': '<div class="comment"><div class="content"><a class="author">'+str(discussion.user.username)+'</a><div class="metadata"><div class="date">'+str(discussion.time)+'</div></div><pre class="ui segment" style="background-color: #f8f8f8;border:0px;">'+str(discussion.message)+'</pre></div></div>'})
	return HttpResponse("success")


def delcom(request):
	com=request.POST.get('com')
	Discussion.objects.filter(id=com).delete()
	return HttpResponse("success")





discussion/templates/discussion/forum.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% block body %}
<title>Codedaemon | Discussion</title>
<script type="text/javascript" src="{% static "js/main.js" %}"></script>
<script>
    $(function() {
        $('.ui.item').hover(function () {
            $(this).animate({
                'opacity':'1'
            }).css({'background-color':'#e7ebf0','color':'#6a86a4'});
        }, function () {
            $(this).animate({
                'opacity':'0.7'
            }).css({'background':'none','color':'black'});;
        });
    });
    var countDownDate = new Date("{{end}}").getTime();
    var x = setInterval(function() {
        var now = new Date().getTime();
        var distance = countDownDate - now;
        var days = Math.floor(distance / (1000 * 60 * 60 * 24));
        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((distance % (1000 * 60)) / 1000);
        document.getElementById("demo").innerHTML = days + "d " + hours + "h "
        + minutes + "m " + seconds + "s ";
        if (distance < 0) {
            clearInterval(x);
            document.getElementById("demo").innerHTML = "LOCKED";
            document.getElementById("demo").style = "color:red";
        }
    }, 1000);

    function delete_com(id) {
        $.post("{% url 'discussion:delcom' %}", {'com':id,'csrfmiddlewaretoken': '{{ csrf_token }}'}, function(data) {
          window.location.href = "{% url 'discussion:disc' contest_id %}";
         });
    }
  </script>
<body style="background-color:#f3f3f3" onload="setupWebSocket();">
<br>
<div class="ui container">
  <div class="ui breadcrumb" style="background-color:#f3f3f3;">
    <a class="section" id="con_name" href="{% url 'home:contest_info' contest.id %}" >{{ contest.con_name }}</a>
    <i class="right angle icon divider"></i>
    <div class="active section">Leaderboard</div>
  </div>

  <div class="ui blue secondary pointing menu">
    <a class="ui item" href="{% url 'home:contest_details' contest.id %}">
        Problem
      </a>
      <a class="ui item" href="{% url 'Leader:leader' contest.id %}">
        Leaderboard
      </a>
      <a class="ui active item" href="{% url 'discussion:disc' contest.id %}">
        Discussions
      </a>
      <div class="right menu">
        <a class="ui item">
          TIME  : <span id="demo" style="color:#3498DB;"></span>
        </a>
        <a class="ui item">
          RANK  : <span style="color:#3498DB;">{{ Rank }}</span>
        </a>
      </div>
  </div>
</div>
<br>
<br>
<div class="ui container">
  <div class="ui comments">
    <div class="comment">
      <div class="content">
        <a class="author">{{request.session.user}}</a>
        <div class="metadata">
          <div class="date">2 days ago</div>
        </div>
        <form class="ui reply form">
          <div class="field">
            <textarea id="comment"></textarea>
          </div>
          <div class="ui primary submit labeled icon button" id="sadd">
            <i class="icon edit"></i> Add Reply
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="ui comments" id = "discuss">

  {% for i in All %}
    <div class="comment">
    <div class="content">
      <a class="author">{{ i.user.username }}</a>
      <div class="metadata">
          <div class="date">{{i.time}}</div>
        {% if i.user.username == request.session.user  %}
          <button class="ui mini button" id="sdel{{ i.id }}" onclick="delete_com({{ i.id }})">DELETE</button>
        {% endif %}
      </div>
      <pre class="ui segment" style="background-color: #f8f8f8;border:0px;">{{ i.message }}</pre>
    </div>
    </div>
{% endfor %}
  </div>
</div>

<script type="text/javascript">
  $(function() {

  $('#sadd').click(function() {
	if ($('#comment').val() =="")
		return false;
          $.post("{% url 'discussion:addcom' %}", {'con':{{ contest_id }},'comment':$('#comment').val() , 'csrfmiddlewaretoken': '{{ csrf_token }}'}, function(data) {
         });
        });
    });
</script>
{% endblock %}