Leader/urls.py
from . import  views
from django.conf.urls import url

app_name='Leader'

urlpatterns = [
    url(r'^create/(?P<cont_id>[0-9]+)$',views.index,name='index'),
    url(r'^(?P<cont_id>[0-9]+)$',views.leader ,name='leader'),
    url(r'(?P<uname>[0-9A-Za-z_]+)$',views.get_user,name='user'),
]

Practice/urls.py
from django.conf.urls import url
from . import views


app_name = 'Practice'

urlpatterns = [
    url(r'^$',views.index,name='index'),
]

Reverse/urls.py
from django.conf.urls import url
from . import views


app_name = 'Reverse'
'''
app_name is added bcoz name of 
'''
urlpatterns = [
    url (r'^check/(?P<problem_name>[0-9A-Za-z_]+)/$',views.check,name='check'),
    url (r'^(?P<problem_name>[0-9A-Za-z_]+)/$',views.index,name='index'),
]

codedaemon/urls.py
from django.contrib import admin
from django.conf.urls import include,url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls')),
    url(r'^past_contest/', include('Practice.urls')),
    url(r'^reverse/', include('Reverse.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^discussion/', include('discussion.urls')),
    url(r'^Compile_run/', include('Compile_run.urls')),
    url(r'^Leader/', include('Leader.urls')),
    url(r'^adminpanel/',include('adminpanel.urls')),
]

discussion/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from . import views

app_name='discussion'
urlpatterns = [
    url(r'^(?P<contest_id>[0-9]+)/$', views.disc,name='disc'), 
    url(r'^addcom/$',views.addcom,name='addcom'), 
    url(r'^delcom/$', views.delcom,name='delcom'), 
]


home/urls.py
from django.conf.urls import url,include
from . import views
app_name='home'
urlpatterns = [
    url(r'^$',views.contest,name='contest'),
    url(r'^(?P<contest_id>[0-9]+)/contest_details/$',views.contest_details,name='contest_details'),
    url(r'^(?P<contest_id>[0-9]+)/contest_info/$',views.contest_info,name='contest_info'),
    #url(r'^problem/(?P<problem_id>[0-9]+)/$',views.problem,name='problem'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^onsearch/$',views.onsearch,name='onsearch'),
    url(r'^profile/$',views.profile,name='profile'),
    url(r'^profileupdate/$',views.profileUpdate,name='profileUpdate'),
    url(r'^(?P<contest_id>[0-9]+)/contest_signup/$',views.contest_signup,name='contest_signup'),
    url(r'^contact_us/$',views.contactPage,name='contactPage'),
    url(r'^contact/$',views.contact,name='contact'),
]

home/models.py
from django.db import models
from login.models import User
# Create your models here.
class Contest(models.Model):
	con_name=models.CharField(max_length=250)
	con_date=models.DateField(blank=True)
	start_time=models.DateTimeField(blank=True)
	start = models.CharField(max_length=100)
	end_time=models.DateTimeField(blank=True)
	end = models.CharField(max_length=100)
	org_name=models.CharField(max_length=250)
	image=models.CharField(max_length=250)
	tagline=models.CharField(max_length=250)
	disc=models.TextField()
	rules=models.TextField()
	prize=models.TextField()
	scoring=models.TextField()
	signups=models.IntegerField(default=0)

	def __str__(self):
	    return "Contest Name : %s Contest id %d" % (self.con_name,self.id)

class Problem(models.Model):
	Contest=models.ForeignKey(Contest,on_delete=models.CASCADE)
	p_name=models.CharField(max_length=250)	#name
	r_flag=models.BooleanField(default=False)
	p_level=models.CharField(max_length=250)
	p_disc=models.TextField() # description
	p_input=models.TextField() # input Format
	p_cons=models.TextField() # constraints
	p_output=models.TextField() # o/p format
	sample_input=models.TextField()
	sample_output=models.TextField()
	exp=models.TextField() #explanations
	# From Compile_run

	success_sub = models.IntegerField(default=0) # for suces rate
	tot_sub = models.IntegerField(default=0)
	score = models.IntegerField() #Total score
	s_rate = models.IntegerField()

	def __str__(self):
		if(self.tot_sub == 0):
		    return "\nProblem Id : %s -- %s - Success Rate : %.2f - Score : %d" % (self.p_name,self.success_sub,0,self.score)
		else:
		    return "\nProblem Id : %s -- %s - Success Rate : %.2f - Score : %d" % (self.p_name,self.success_sub,(((self.success_sub*1.0) / self.tot_sub)*100),self.score)


class Con_signup(models.Model):
	contest=models.ForeignKey(Contest,on_delete=models.CASCADE)
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	status=models.BooleanField(default=False)
	def __str__(self):
		return self.contest.con_name + " "+self.user.username


class Contact(models.Model):
	name=models.CharField(max_length=250)
	email=models.CharField(max_length=250)
	sub=models.CharField(max_length=250)
	message=models.CharField(max_length=250)

home/views.py
from django.shortcuts import render,get_object_or_404
from .models import Contest,Problem,Con_signup,Contact
from login.models import User
from django.utils import timezone
import time
from django.http import HttpResponse
from django.apps import apps
from login.models import User
from django.apps import apps
from Compile_run.models import User_Problem
from django.contrib.auth.decorators import login_required

def get_u(request):
	try:
		u = request.session['user']
	except:
		return ''
	return u

def get_rank(user,contest_id):
	cont=apps.get_model(app_label='Leader', model_name="cont_"+str(contest_id))
	me = cont.objects.get(user=User.objects.get(id=user))
	all_users  = cont.objects.all()
	for rank,u in enumerate(all_users):
		if u == me:
			return rank+1

@login_required
def contest(request):
	try:
		con=Contest.objects.filter(end_time__gt=timezone.now())
		con_signup = Con_signup.objects.filter(user=get_object_or_404(User,username=get_u(request)))
		signups = Con_signup.objects.all()
		contestlist=[]
		for x in con_signup:
			contestlist.append(x.contest)
	except Contest.DoesNotExist:
		raise Http404("contest does not exits")
	return render(request,'home/contest.html',{'con':con,'con_sign':contestlist,'arr':['','active','','','']})

def contest_details(request,contest_id):
	try:
		contest=Contest.objects.get(pk=contest_id)
		user = get_object_or_404(User,username=get_u(request))
		con_signup = Con_signup.objects.filter(user=get_object_or_404(User,username=get_u(request)))
		contestlist=[]
		for x in con_signup:
			contestlist.append(x.contest)
	except Contest.DoesNotExist:
		raise Http404("Contest does not exits")

	problems = Problem.objects.filter(Contest=contest)
	problems = problems.order_by('-s_rate')
	solved_status = []
	j = 1
	for i in problems:
		Us_Pro = User_Problem.objects.filter(User=user, Problem=i).first()
		if Us_Pro is None:
			solved_status.append(0)
		elif Us_Pro.status:
			solved_status.append(1)
		else :
			solved_status.append(2)
		j+=1
	print solved_status
	print(str(contest.end_time)[:16:]);
	if contest.start_time  <= timezone.now():
		return render(request,'home/contest_details.html',{'contest':contest,'end':str(contest.end_time)[:16:],'Rank':get_rank(user.id,contest.id),'problems_status':zip(problems,solved_status)})
	else :
		return render(request,'home/contest.html',{'con':Contest.objects.all(),'con_sign':contestlist})



def contest_info(request,contest_id):
	try:
		contest=Contest.objects.get(pk=contest_id)
		user = get_object_or_404(User,username=get_u(request))
	except Contest.DoesNotExist:
		raise Http404("Contest does not exits")
	problems = Problem.objects.filter(Contest=contest)
	solved_status = []
	j = 1
	for i in problems:
		Us_Pro = User_Problem.objects.filter(User=user, Problem=i).first()
		if Us_Pro is None:
			solved_status.append(0)
		elif Us_Pro.status:
			solved_status.append(1)
		else :
			solved_status.append(2)
		j+=1
	#print solved_status
	if contest.start_time  <= timezone.now():
		return render(request,'home/contest_details.html',{'contest':contest,'end':str(contest.end_time)[:16:],'Rank':get_rank(user.id,contest.id),'problems_status':zip(problems,solved_status)})
	else :
		return render(request,'home/con_signup.html',{'contest':contest,'end':str(contest.end_time)[:16:],'solved_status':solved_status})

def contest_signup(request,contest_id):
	print 'con_signup'
	try:
		contest=Contest.objects.get(pk=contest_id)
	except Contest.DoesNotExist:
		raise Http404("Contest does not exits")
	user = get_object_or_404(User,username=get_u(request))
	if Con_signup.objects.filter(contest=contest,user=user).first() is None :
		print 'signed up'
		con_signup=Con_signup(contest=contest,user=user,status=True)
		con_signup.save()
		cont_Leader=apps.get_model(app_label='Leader', model_name="cont_"+str(contest_id))
		new_rec = cont_Leader(user = user,sub_time=contest.start_time)
		new_rec.save()
		contest.signups=contest.signups+1
		contest.save()
	return render(request,'home/con_signup.html',{'contest':contest,'end':str(contest.end_time)[:16:]})

def logout(request):
	request.session['user'] = ''
	return render(request,'login/index.html')


def onsearch(request):
	if 	request.method == 'POST':
		keywords = request.POST.get('Keywords')
		res = Problem.objects.filter(p_name__contains=keywords)
		result = ''
		for i in res :
			result += i.p_name+'\n'
		print (str(result))
		return HttpResponse(str(result))

def profile(request):
	data=get_object_or_404(User,username=get_u(request))
	return render(request,'home/profile.html',{'data':data,'arr':['','','','','active']})

def profileUpdate(request):
	data=get_object_or_404(User,username=get_u(request))
	data.clgname=request.POST.get('clgname')
	data.languages=request.POST.get('languages')
	data.experience=request.POST.get('experience')
	data.save()
	return render(request,'home/profile.html',{'data':data})

def contactPage(request):
	return render(request,'home/contact.html',{'arr':['','','','active','']})

def contact(request):
	if request.method=='POST':
		fd=Contact(name=request.POST.get('name'),email=request.POST.get('email'),sub=request.POST.get('sub'),message=request.POST.get('message'))
		fd.save()
		msg='success'
		return HttpResponse(msg)
	else:
		return HttpResponse("fail")

home/templates/home/base.html
{% load staticfiles %}
{% if not request.session.user %}
<div>
  You are not logged in
</div>
{% else %}

<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'Semantic/semantic.min.css' %} "/>
<script src="{% static 'Semantic/semantic.min.js' %}"></script>
<body style="background-color:#f3f3f3">
 <div class="ui blue large secondary pointing menu">
   <a class="ui large item " href="{% url 'home:contest' %}">
     Codedaemon
   </a>
   <div class="right menu">
     <a class="ui item {{ nav.contest }} {{arr.1}}" href="{% url 'home:contest' %}">
       Contest
     </a>
     <a class="ui item {{ nav.practice }} {{arr.2}}" href="{% url 'Practice:index' %}">
       Practice
     </a><a class="ui item {{ nav.contact }} {{arr.3}}" href="{% url 'home:contactPage' %}">
       Contact
     </a>
     <a class="ui item {{ nav.profile }} {{arr.4}}" href="{% url 'home:profile' %}">
     <img class="ui avatar image" src="{% static 'square-image.png' %}">
       <span>{{ request.session.user }}</span>
     </a>
     <div class="item">
         <a class="ui basic blue button" href="{% url 'home:logout' %}">Logout</a>
     </div>
   </div>
 </div>
{% block body %}
{% endblock %}
{% endif %}

home/templates/home/con_signup.html
{% extends 'home/base.html' %}
{% load staticfiles %}
<div class="container">
<div class="back">
  {% block body %}
<center>
	<strong class="name" style="margin-top:100px;">{{ contest.con_name }}</strong>
</center>
<br>
<center>
	<strong class="name" style="margin-top:100px;">{{ contest.con_date }}</strong>
</center>
<br>
<center>
	<strong class="name" style="margin-top:100px;">{{ contest.start_time }}----{{ contest.end_time }}</strong>
</center>
<br>
<center>
	<strong class="name" style="margin-top:100px;">{{ contest.org_name }}</strong>
</center>
<br>
<center>
	<strong class="ui black mini button" style="margin-top:100px;"><a href = "{% url 'home:contest_info' contest.id %}">Enter</a></strong>
</center>
</div>
<div class="col-sm-12 main">
	<strong class="data" style="margin-top:100px;">PRIZE</strong>
  <div>
    {{ contest.prize}}
  </div>
</div>
<hr>
<div class="col-sm-12 main">
	<strong class="data" style="margin-top:100px;">RULE</strong>
    <div>
    {{ contest.rules}}
  </div>
</div>
<hr>
<div class="col-sm-12 main">
	<strong class="data" style="margin-top:100px;">SCORING</strong>
    <div>
    {{ contest.scoring}}
  </div>
</div>
<hr>
</div>
{% endblock %}

home/templates/home/contact.html

    <meta charset="UTF-8">

    <title>Codedaemon | contact</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

{% extends 'home/base.html' %}
{% load staticfiles %}
{% block body %}
 <br>
 <br>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-lg-12">
                <h3>
                   CONTACT US <small></small></h3>
            </div>
        </div>
    </div>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="well well-sm" >

                <div class="row">
                <div class="col-md-1"></div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="name">
                                Name</label>
                            <input type="text" class="form-control" id="name" placeholder="Enter name" required="required" />
                        </div>
                        <div class="form-group">
                            <label for="email">
                                Email</label>

                                <input type="email" class="form-control" id="email" placeholder="Enter email" required="required" /></div>

                        <div class="form-group">
                        <label for="sub">
                                Subject:</label>
                            <input type="text" class="form-control" id="sub" placeholder="Enter subject" required="required" />
                        </div>

                        <div class="form-group">
                            <label for="name">
                                Message</label>
                            <textarea name="message" id="message" class="form-control" rows="9" cols="25" required="required"
                                placeholder="Message"></textarea>
                        </div>

                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary pull-right" style="background-color:black;" id="us">
                            Send</button>
                    </div>


            </div>
                </div>


            </div>
        </div>
        <div class="col-md-4">
            <form>
            <legend><span class="glyphicon glyphicon-globe"></span>&nbsp;DEVELOPER TEAM</legend>
            <address>

                <ul class="name">
                    <li>Onkar Sathe</li>
                    <li>Vaibhav Thombre</li>
                    <li>Shubham Kharose</li>
                    <li>Ajay Kulkarni</li>
                    <li>Ritesh Harel</li>
                </ul>
                <i class="fa fa-map-marker" aria-hidden="true"></i>&nbsp;<span>Walchand college of engineering,Sangli</span>
            </address>

            </form>
        </div>
    </div>
</div>
</body>


    <script type="text/javascript">

  $(function() {

        $('#us').click(function() {
        var name = document.getElementById('name').value;
        var email=document.getElementById('email').value;
        var sub=document.getElementById('sub').value;
        var message=document.getElementById('message').value;
          // You gotta include the csrf_token in your post data
          $.post('/home/contact/', {'name': name,'email':email,'sub':sub,'message':message, 'csrfmiddlewaretoken': '{{ csrf_token }}'}, function(data) {
            if(data == 'success')
              alert('Thanks For Contact us..!!!')
            else
              alert('Invalid');
             // append to inner html
            //alert(data);
         });
      });
    });

  </script>
{% endblock %}

home/templates/home/contest.html
 <title>Codedaemon | CONTEST</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
{% extends 'home/base.html' %}
{% load staticfiles %}
{% block body %}<script>
    $(function() {
        $('.ui.item').hover(function () {
            $(this).animate({
                'opacity':'1'
            }).css({'background-color':'#e7ebf0','color':'#6a86a4'});
        }, function () {
            $(this).animate({
                'opacity':'0.7'
            }).css({'background':'none','color':'black'});;
        });
    });
  </script>
{% if con %}
<div class="ui container">
  <div class="ui link cards">
  {% for con in con %}
  <script>
    var x = setInterval(function() {
        var countDownDate = new Date("{{con.start}}").getTime();
        var now = new Date().getTime();
        var countDownDateEnd = new Date("{{con.end}}").getTime();
        var distance = countDownDate - now;
        var activedistance=countDownDateEnd-now;
        var days = Math.floor(distance / (1000 * 60 * 60 * 24));
        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((distance % (1000 * 60)) / 1000);
        document.getElementById("demo{{con.id}}").innerHTML = ""+days + "d " + hours + "h "
        + minutes + "m " + seconds + "s ";

        if (now > countDownDate && now < countDownDateEnd) {

            document.getElementById("demo{{con.id}}").innerHTML = "ACTIVE";
            document.getElementById("demo{{con.id}}").style = "color:green";
        }
        else if(now > countDownDateEnd)
        {
            document.getElementById("demo{{con.id}}").innerHTML = "ENDED";
            document.getElementById("demo{{con.id}}").style = "color:red";
        }

       },
  1000);
  </script>
    <div class="card">
      <div class="image">
        <img src="{% static 'home/images/image.jpg' %}">
      </div>
      <div class="content">
        <div class="header">{{ con.con_name }}</div>
        <div class="meta">
          <a>Signups {{ con.signups }}</a>
        </div>
        <center>
        <div class="ui label description" id="demo{{con.id}}">
        </div>
        </center>
      </div>
      <div class="extra content">

        <span class="floated">
          {{ con.start_time}}
        </span>
        <span class=" floated">
          <a class="ui tag label">START</a>
        </span>
      </div>

      <div class="extra content">
        <span class="floated">
          {{ con.end_time}}
        </span>
        <span class=" floated">
          <a class="ui tag label">END</a>
        </span>
      </div>
      <div class="extra content">
        <span class="floated">
          {% if con in con_sign %}
            <center><a href="{% url 'home:contest_details' con.id %}" class="ui blue mini button">ENTER</a></center>
          {% else %}
            <center><a href="{% url 'home:contest_signup' con.id %}" class="ui blue mini button">SIGNUP</a></center>
          {% endif %}
        </span>
    </div>
  </div>
{% endfor %}
</div>
</div>
{% else %}
  <h3>No active contest exits, You can solve problems in <a href="{% url 'Practice:index' %}">Practice</a> Section</h3>
{% endif %}
</div>
{% endblock %}

home/templates/home/contest_details.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% block body %}
<title>Codedaemon | Discussion</title>
<script>
    $(function() {
        $('.ui.item').hover(function () {
            $(this).animate({
                'opacity':'1'
            }).css({'background-color':'#e7ebf0','color':'#6a86a4'});
        }, function () {
            $(this).animate({
                'opacity':'0.7'
            }).css({'background':'none','color':'black'});;
        });
    });
    var countDownDate = new Date("{{end}}").getTime();
    var x = setInterval(function() {
        var now = new Date().getTime();
        var distance = countDownDate - now;
        var days = Math.floor(distance / (1000 * 60 * 60 * 24));
        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((distance % (1000 * 60)) / 1000);
        document.getElementById("demo").innerHTML = days + "d " + hours + "h "
        + minutes + "m " + seconds + "s ";
        if (distance < 0) {
            clearInterval(x);
            document.getElementById("demo").innerHTML = "LOCKED";
            document.getElementById("demo").style = "color:red";
        }
    }, 1000);

  </script>
<br>
<div class="ui container">
  <div class="ui breadcrumb" style="background-color:#f3f3f3;">
    <a class="section" href="{% url 'home:contest_details' contest.id %}">{{ contest.con_name }}</a>
    <i class="right angle icon divider"></i>
    <div class="active section">Leaderboard</div>
  </div>

  <div class="ui blue secondary pointing menu">
    <a class="ui active item" href="{% url 'home:contest_details' contest.id %}">
        Problem
      </a>
      <a class="ui item" href="{% url 'Leader:leader' contest.id %}">
        Leaderboard
      </a>
      <a class="ui item" href="{% url 'discussion:disc' contest.id %}">
        Discussions
      </a>
      <div class="right menu">
        <a class="ui item">
          TIME  : <span id="demo" style="color:#3498DB;"></span>
        </a>
        <a class="ui item">
          RANK  : <span style="color:#3498DB;">{{ Rank }}</span>
        </a>
      </div>
  </div>

  <div class="ui grid">
    <div class="one wide column">
    </div>
    <div class="fourteen wide column">
      <table class="ui very basic table">
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
            <th>Marks</th>
            <th>Level</th>
            <th>Success Rate</th>
          </tr>
        </thead>
        <tbody>
          {% for problem , status in problems_status %}
          <tr>
            {% if problem.r_flag %}
            <td><a href="{% url 'Reverse:index' problem.p_name %}">{{ problem.p_name }}</a></td>
            {% else %}
            <td><a href="{% url 'Compile_run:index' problem.p_name %}">{{ problem.p_name }}</a></td>
            {% endif %}
            {% if status is 1 %}
            <td><i class="green checkmark icon"></i></td>
            {% elif status is 2%}
            <td><i class="red remove icon"></td>
            {% else %}
            <td></td>
            {% endif %}
            <td>{{ problem.score }}</td>
            <td>{{ problem.p_level }}</td>
            <td>{{ problem.s_rate }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

home/templates/home/problem.html
{% extends 'home/base.html' %}
{% block body %}
{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="" method="post">
{% csrf_token %}

	<div class="box" style="border-style:solid;border-width:2px;">
	<a href="" style="font-size:30px">{{ problem.id}}-{{ problem.p_name }}</a>&nbsp;&nbsp;&nbsp;
	<strong>MARKS:</strong>
	&nbsp;
	<a>{{ problem.p_mark }}</a>
	&nbsp;&nbsp;
	<strong>LEVEL:</strong>
	&nbsp;
	<a>{{ problem.p_level }}<a>
	<br>
	<hr>
	<br>
	<strong>STATEMENT:</strong>
	<p>{{ problem.p_disc }}<p>
	<strong>INPUT FORMAT:</strong>
	<p>{{ problem.p_input }}<p>
	<strong>CONSTRAINT:</strong>
	<p>{{ problem.p_cons }}<p>
	<strong>OUTPUT FORMAT:</strong>
	<p>{{ problem.p_output }}<p>
	<strong>SAMPLE INPUT:</strong>
	<p>{{ problem.sample_input }}<p>
	<strong>SAMPLE OUTPUT:</strong>
	{{ problem.sample_output }}<p>
	<strong>EXPLANATION:</strong>
	<p>{{ problem.exp }}<p>

	<input type="text" name="text" style="height:500px;width:600px"><br>
	<center><input type="submit" value="enter"></center>
	</div>


</form>
{% endblock %}