Compile_run/urls.py
from django.conf.urls import url
from . import views


app_name = 'Compile_run'
'''
app_name is added bcoz name of 
'''
urlpatterns = [
    url (r'^(?P<problem_name>[0-9A-Za-z_]+)/$',views.index,name='index'),
    url (r'^run/(?P<problem_id>[0-9]+)/', views.run, name='run'),
    url (r'^submit/(?P<problem_id>[0-9]+)/', views.submit, name='submit'),
    url (r'^change/(?P<problem_id>[0-9]+)/', views.change, name='change'),
    url (r'^code/(?P<problem_id>[0-9]+)/(?P<sub_id>[0-9]+)/', views.code, name='code'),
]

Leader/urls.py
from . import  views
from django.conf.urls import url

app_name='Leader'

urlpatterns = [
    url(r'^create/(?P<cont_id>[0-9]+)$',views.index,name='index'),
    url(r'^(?P<cont_id>[0-9]+)$',views.leader ,name='leader'),
    url(r'(?P<uname>[0-9A-Za-z_]+)$',views.get_user,name='user'),
]

Reverse/urls.py
from django.conf.urls import url
from . import views


app_name = 'Reverse'
'''
app_name is added bcoz name of 
'''
urlpatterns = [
    url (r'^check/(?P<problem_name>[0-9A-Za-z_]+)/$',views.check,name='check'),
    url (r'^(?P<problem_name>[0-9A-Za-z_]+)/$',views.index,name='index'),
]

codedaemon/urls.py
from django.contrib import admin
from django.conf.urls import include,url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls')),
    url(r'^past_contest/', include('Practice.urls')),
    url(r'^reverse/', include('Reverse.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^discussion/', include('discussion.urls')),
    url(r'^Compile_run/', include('Compile_run.urls')),
    url(r'^Leader/', include('Leader.urls')),
    url(r'^adminpanel/',include('adminpanel.urls')),
]

discussion/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from . import views

app_name='discussion'
urlpatterns = [
    url(r'^(?P<contest_id>[0-9]+)/$', views.disc,name='disc'), 
    url(r'^addcom/$',views.addcom,name='addcom'), 
    url(r'^delcom/$', views.delcom,name='delcom'), 
]


home/urls.py
from django.conf.urls import url,include
from . import views
app_name='home'
urlpatterns = [
    url(r'^$',views.contest,name='contest'),
    url(r'^(?P<contest_id>[0-9]+)/contest_details/$',views.contest_details,name='contest_details'),
    url(r'^(?P<contest_id>[0-9]+)/contest_info/$',views.contest_info,name='contest_info'),
    #url(r'^problem/(?P<problem_id>[0-9]+)/$',views.problem,name='problem'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^onsearch/$',views.onsearch,name='onsearch'),
    url(r'^profile/$',views.profile,name='profile'),
    url(r'^profileupdate/$',views.profileUpdate,name='profileUpdate'),
    url(r'^(?P<contest_id>[0-9]+)/contest_signup/$',views.contest_signup,name='contest_signup'),
    url(r'^contact_us/$',views.contactPage,name='contactPage'),
    url(r'^contact/$',views.contact,name='contact'),
]

Reverse/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from home.models import Contest,Problem
# Create your models here.
class Reverse(models.Model):
	Problem = models.ForeignKey(Problem,on_delete=models.CASCADE)
	code=models.FileField()
	

Reverse/views.py
from django.http import HttpResponse
from django.shortcuts import render,get_object_or_404
from Compile_run.models import User_Problem,TestCase,Problem_session,AdminSettings
import subprocess
from django.template import loader
import datetime
from threading import Thread
import time
import json
from home.models import Problem,Contest
from login.models import User 
from django.apps import apps
from Leader import create,views
import select
from login.models import User
from django.apps import apps
from django.utils.html import escape
import signal,os
from signal import SIG_DFL
from .models import Reverse
from Compile_run.views import get_rank

from home.views import get_u

def getWelO(ans):
	s1 = ans.split("\n")
	s2 = []
	
	for string in s1 :
		string = string.strip(" ")
		string = string.strip("\r")
		if string is "\n" or string == '':
			continue
		s2.append(string)
	ans = '\n'.join(s2)
	return ans

def getO(command,timeout):	
	poll_obj = select.poll()
	poll_obj.register(command.stdout, select.POLLIN)
	buflimit = AdminSettings.objects.get(id=1).buff
	buf = 0
	ans =''
	start = time.time()
	idealbuffer =1
	while buf <= buflimit and start + timeout > time.time() : 
		poll_result = poll_obj.poll(0)
		if poll_result:
			ans+= command.stdout.read(idealbuffer)
			buf+=idealbuffer
	return getWelO(ans)



def index(request,problem_name):
	problem = Problem.objects.get(p_name=problem_name)
	R_problem = Reverse.objects.get(Problem=problem)
	contest = problem.Contest
	session = Problem_session.objects.get(Problem=problem).c_session_code
	user=get_object_or_404(User,username=get_u(request))

	Us_Pro = User_Problem.objects.filter(User=user, Problem=problem).first()

	Submission = apps.get_model(app_label='Leader', model_name="Sub_cont_"+str(problem.Contest.id))
	all_sub=Submission.objects.filter(User=user,Problem=problem)
	meta = ['id','time','pts','Lang']
	time = contest.start_time
	time = time.replace(microsecond=0)
	sub_table=create.get_sub(all_sub,meta,time)
	meta = ['Code','Sub time','Score','Lang']
	if Us_Pro is None:
		return render(request, 'reverse.html',{'session':session,'Lang':'c','problem':problem ,'contest':contest,'sub_all':sub_table,'fields':meta,'end':str(contest.end_time)[:16:],'Rank':get_rank(user.id,contest.id),'S_Rate':problem.s_rate})
	else:
		if Us_Pro.last_lang == 'c':
			session = Us_Pro.c_session_code
		elif Us_Pro.last_lang == 'c_cpp':
			session = Us_Pro.cpp_session_code
		elif Us_Pro.last_lang == 'java':
			session = Us_Pro.java_session_code
		elif Us_Pro.last_lang == 'python' :
			session = Us_Pro.py_session_code
		elif Us_Pro.last_lang == 'python3' :
			session = Us_Pro.py3_session_code
		return render(request, 'reverse.html',{'session':session,'Lang':Us_Pro.last_lang,'problem':problem ,'contest':contest,'sub_all':sub_table,'fields':meta,'end':str(contest.end_time)[:16:],'Rank':get_rank(user.id,contest.id),'Status':Us_Pro.status,'S_Rate':problem.s_rate})
	

def check(request,problem_name):
	problem = Problem.objects.get(p_name=problem_name)
	R_problem = Reverse.objects.get(Problem=problem)
	input_for = request.POST.get('input')
	command = subprocess.Popen ("python "+R_problem.code.name, shell=True, stdout=subprocess.PIPE,stderr=subprocess.STDOUT, stdin=subprocess.PIPE)
	command.stdin.write (input_for)
	command.stdin.close ()
	ans = ''
	ans = getO(command,2)
	return HttpResponse(ans)

Reverse/templates/reverse.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% block body %}


<!-- Author : Onk_r -->



  <title>Problem</title>
  <script type="text/javascript">
  $('.ui.dropdown')
  .dropdown();

  $(function() {
    $('.ui.item').hover(function () {
        $(this).animate({
            'opacity':'1'
        }).css({'background-color':'#e7ebf0','color':'#6a86a4'});
    }, function () {
        $(this).animate({
            'opacity':'0.7'
        }).css({'background':'none','color':'black'});;
    });

    $('#addtextbox').click(function(){
      if ($(this).is(':checked')) {
        $('#dynamic').html("<textarea id=\"input_from_user\" name=\"output\" rows=\"10\" cols=\"10\"></textarea>");
      }
      else if (!$(this).is(':checked')) {
        $('#dynamic').html("");
      }
    });

    $('#check').click(function(){
      var input_for = document.getElementById('input_for').value;
	  $('#check').attr('disabled',true).addClass('loading');
	  $.post('/reverse/check/{{problem.p_name}}/', {'input':input_for,'csrfmiddlewaretoken': '{{ csrf_token }}'}, function(data){
	    $('#reverse').html(data);

	    $('#check').attr('disabled',false).removeClass('loading');
		});
    });
    $('#mybutton').click(function() {
      $(this).attr('disabled',true);
        $('#mybutton').attr('disabled',true).addClass('loading');
        var Lang = document.getElementById('Lang').value;
        var Code = (editor.getValue()); 
        $.post('/Compile_run/submit/{{ problem.id }}/', {'code': Code,'lang':Lang, 'csrfmiddlewaretoken': '{{ csrf_token }}'}, function(data){
        $('#output2').html(data);
        $('html, body').animate({ scrollTop:$(document).height()-$(window).height()},"fast");  
        $('#mybutton').attr('disabled',false).removeClass('loading');
        });
    });

    $('#mybutton1').click(function() {
      if ($('#addtextbox').is(':checked')) {
        $('#output2').html("");
        $('#mybutton1').attr('disabled',true).addClass('loading');
        var dyan = document.getElementById('input_from_user').value;

        var Lang = document.getElementById('Lang').value;
        var Code = (editor.getValue()); 
        var status = 'yes';
        $.post('/Compile_run/run/{{ problem.id }}/', {'code': Code,'lang':Lang,'Check_Status':status,'input':dyan, 'csrfmiddlewaretoken': '{{ csrf_token }}'}, function(data){
          $('#output2').html("<p><strong class=\"header\">Input</strong></p><pre class=\"ui segment\" style=\"background-color: #f8f8f8;border:0px;\">"+dyan+"</pre><p><strong class=\"header\">Your Output</strong></p>"+"<pre class=\"ui segment\" style=\"background-color: #f8f8f8;border:0px;\">"+data);
          $('html, body').animate({ scrollTop:$(document).height()-$(window).height()},"fast");  
        $('#mybutton1').attr('disabled',false).removeClass('loading');
        });
      }
      else if (!$('#addtextbox').is(':checked')) {
        $('#output2').html("");
        $('#mybutton1').attr('disabled',true).addClass('loading');
        var Lang = document.getElementById('Lang').value;
        var Code = (editor.getValue()); 
        $.post('/Compile_run/run/{{ problem.id }}/', {'code': Code,'lang':Lang, 'csrfmiddlewaretoken': '{{ csrf_token }}'}, function(data){
          $('#output2').html("<p><strong class=\"header\">Input</strong></p><pre class=\"ui segment\" style=\"background-color: #f8f8f8;border:0px;\">{{ problem.sample_input|escapejs}}</pre><p><strong class=\"header\">Your Output</strong></p>"+data);
        $('html, body').animate({ scrollTop:$(document).height()-$(window).height() },"fast");    
        $('#mybutton1').attr('disabled',false).removeClass('loading');
        });
      }
      
    });
    $('#Lang').change(function() {
      var Lang = document.getElementById('Lang').value;

          $.post('/Compile_run/change/{{ problem.id }}/', {'lang':Lang, 'csrfmiddlewaretoken': '{{ csrf_token }}'}, function(data){
            //alert(data);
            editor.setValue(data);
        });
      });
    
  });
  </script>
  <script type="text/javascript">
    function fun(){
      var lang = document.getElementById('Lang').value;
      if(lang == 'c') {
        editor.session.setMode("ace/mode/" + lang + '_cpp');
      }
      else if(lang =='python3') {
        editor.session.setMode("ace/mode/python");
      }
      else {
        editor.session.setMode("ace/mode/" + lang);
      }
    }
    function setLang(){
      var lang = '{{ Lang }}';
      document.getElementById('Lang').value = lang;
      if(lang == 'c') {
        editor.session.setMode("ace/mode/" + lang + '_cpp');
      }
      else if(lang =='python3') {
        editor.session.setMode("ace/mode/python");
      }
      else {
        editor.session.setMode("ace/mode/" + lang);
      }
    }
  </script>
  <style>
    div.col {
        float: left;
        width: 50%;
    }
  </style>
<body onload="setLang()" style="background-color:#f3f3f3">
  <div class="ui blue large secondary pointing menu">
    <a class="ui item " href="{% url 'home:contest' %}">
      Codedaemon
    </a>
    <div class="right menu">
      <a class="ui active item" href="{% url 'home:contest' %}">
        Contest
      </a>
      <a class="ui item">
        Practice
      </a><a class="ui item" href="{% url 'home:contactPage' %}">
        Contact
      </a>
      <a class="ui item" href="{% url 'home:profile' %}">
      <img class="ui avatar image" src="{% static 'square-image.png' %}">
        <span>{{ request.session.user }}</span>
      </a>
      <div class="item">
          <a class="ui basic blue button" href="{% url 'home:logout' %}">Logout</a>
      </div>
    </div>
  </div>

<br>
<div class="ui container">
  <div class="ui breadcrumb" style="background-color:#f3f3f3;">
    <a class="section" href="{% url 'home:contest_info' contest.id %}">{{ contest.con_name }}</a>
    <i class="right angle icon divider"></i>
    <div class="active section">{{ problem.p_name}}</div>
  </div>

  <div class="ui blue secondary pointing menu">
    <a class="ui active item" href="{% url 'home:contest_details' contest.id %}">
        Problem
      </a>
      <a class="ui item" href="{% url 'Leader:leader' contest.id %}">
        Leaderboard
      </a>
      <a class="ui item" href="{% url 'discussion:disc' contest.id %}">
        Discussions
      </a>
      <div class="right menu">
        <a class="ui item">
          TIME  : <span id="demo" style="color:#3498DB;"></span>
        </a>
        <a class="ui item">
          RANK  : <span style="color:#3498DB;">{{ Rank }}</span>
        </a>
      </div>
  </div>
  <script>

    var countDownDate = new Date("{{end}}").getTime();
    var x = setInterval(function() {
        var now = new Date().getTime();
        var distance = countDownDate - now;
        var days = Math.floor(distance / (1000 * 60 * 60 * 24));
        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((distance % (1000 * 60)) / 1000);
        document.getElementById("demo").innerHTML = days + "d " + hours + "h "
        + minutes + "m " + seconds + "s ";
        if (distance < 0) {
            clearInterval(x);
            document.getElementById("demo").innerHTML = "LOCKED";
            document.getElementById("demo").style = "color:red";
        }
    }, 1000);

  </script>
  <div class="ui wide ten column grid">
    <div class="ui ten wide column">
        <div class="ui text segment">
        {% if Status == True %}
            <div class="ui tiny ribbon green label">Solved</div>
          {% else %}
            <div class="ui tiny ribbon red label">NotSolved</div>
          {% endif %}
          <div class="ui segment">
            <h2 class="ui header">{{ problem.p_name }}</h2>
            <div class="ui label">
              Marks :
              <div class="detail">{{ problem.score }}</div>
            </div>
            
            <div class="ui label">
              Level :
              <div class="detail">{{ problem.p_level }}</div>
            </div>
            
            <div class="ui label">
              Success Rate :
              <div class="detail">{{ S_Rate }}</div>
            </div>
          </div>
        <br>
        <p>{{ problem.p_disc }}</p>
        <p><strong class="header">Input Format</strong></p>
        <p>{{ problem.p_input }}</p>
        <p><strong class="header">Output Format</strong></p>
        <p>{{ problem.p_output }}</p>
        <p><strong class="header">Constraints</strong></p>
        <p>{{ problem.p_cons }}</p>
        <p><strong class="header">Sample Input</strong></p>
        <pre class="ui segment" style="background-color: #f8f8f8;border:0px;">{{ problem.sample_input }}</pre>
        <p><strong class="header">Sample Output</strong></p>
        <pre class="ui segment" style="background-color: #f8f8f8;border:0px;">{{ problem.sample_output }}</pre>
        <p><strong class="header">Reverse Engine</strong></p>
	        <div class="ui form">
	        	<div class="field">
	        		<textarea id="input_for" rows="3" style="width:270;" cols="5"></textarea>
	        			<button id="check" class="ui mini green button" >check</button>
	        		<textarea id="reverse" rows="3" style="width:270;" cols="5"></textarea>
	        	</div>
	        </div>
        </div>
      </div>
    <div class="ui six wide column" style="overflow:scroll; height:700px;">
      <h2 class="header"><center>My Submissions </center></h2>
      <table class="ui table" >
      <thead>
            <tr>
                  {% for i in fields %}
                      {% if i == "Sub time" %}
                        <th>Time</th>
                      {% else %}
                        <th>{{i}}</th>
                      {% endif %}

                  {% endfor %}
            </tr>
          </thead>
          <tbody>
            {% for sub in sub_all %}
               <tr>
                   {% for i in sub %}
              {% if forloop.counter > 1 %}
                        <td>{{ i }}</td>
              {% else %}
                <td><a class="ui mini button" href="{% url 'Compile_run:code' problem.id i %}" target="_blank">view</a></td>
              {% endif %}
                   {% endfor %} 
               </tr>
             {% endfor %}
          </tbody>
        </table>
    </div>
  </div>
  <div class="ui horizontal divider">
    <h4 class="header">CODE EDITOR</h4>
  </div>

  <div class="ui segment">
      <h2 class="ui left floated header">Enter your code</h2>
      <div align="right" class="ten wide column">  
      <select class="ui selection dropdown item" id="Lang" onchange="fun()" name="Lang">
        <option value="c">C (5.4.0)</option>
        <option value="c_cpp">C++ (5.4.0)</option>
        <option value="java" >Java (1.8.0_131)</option>
        <option value="python">Python (2.7.12)</option>
        <option value="python3">Python (3.5.2)</option>
      </select>
      </div>    
    <div class="ui clearing divider"></div>
    <div id="editor">{{ session }}</div>
    <div class="ui clearing divider"></div>
    <h4 class="ui left floated header">Custom Input </h4>
    <input class="ui checkbox" type="checkbox" id="addtextbox" style="margin-top:3px;">
    <form class="ui form">
    <div id="dynamic" class="field">
    </div>
    </form
    <br>
    <button id="mybutton1" class="ui blue button" >Run</button>
    <button id="mybutton" class="ui blue button" >Submit</button>
    <div class="ui horizontal divider">
      <h4 class="header">Result</h4>
    </div>
    <div id="output2"></div>
    <div id="output3"></div>
  </div>
</div>  

<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.7/ace.js" type="text/javascript" charset="utf-8"></script>
<script>
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/github");
    editor.session.setMode("ace/mode/c_cpp");
  editor.setOptions({
    maxLines: 100,
    minLines: 20,
    autoScrollEditorIntoView: true,
    fontSize: "14pt"        
  });
  editor.renderer.setScrollMargin(10,10, 0, 0);
  editor.$blockScrolling = Infinity ;
</script>
</body>
{% endblock %}