Leader/urls.py
from . import  views
from django.conf.urls import url

app_name='Leader'

urlpatterns = [
    url(r'^create/(?P<cont_id>[0-9]+)$',views.index,name='index'),
    url(r'^(?P<cont_id>[0-9]+)$',views.leader ,name='leader'),
    url(r'(?P<uname>[0-9A-Za-z_]+)$',views.get_user,name='user'),
]

adminpanel/urls.py
from django.conf.urls import url,include
from . import views
app_name='adminpanel'
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^details/$',views.details,name='details'),
    url(r'^addcon/$',views.addcon,name='addcon'),
    url(r'^(?P<con_id>[0-9]+)/$',views.showqus,name='showqus'),
    url(r'^addqus/$',views.addqus,name='addqus'),
    url(r'^editqus/(?P<p_id>[0-9]+)/$',views.editqus,name='editqus'),
    url(r'^allqus/(?P<con_id>[0-9]+)/$',views.allqus,name='allqus'),
    url(r'^addtest/(?P<p_id>[0-9]+)/$',views.addtest,name='addtest'),
    url(r'^savetest/(?P<p_id>[0-9]+)/$',views.savetest,name='savetest'),
    url(r'^savesession/(?P<p_id>[0-9]+)/$',views.savesession,name='savesession'),
    url(r'^addsession/(?P<p_id>[0-9]+)/$',views.addsession,name='addsession'),
    url(r'^editproblem/(?P<p_id>[0-9]+)$',views.editproblem,name='editproblem'),
]

codedaemon/urls.py
from django.contrib import admin
from django.conf.urls import include,url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls')),
    url(r'^past_contest/', include('Practice.urls')),
    url(r'^reverse/', include('Reverse.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^discussion/', include('discussion.urls')),
    url(r'^Compile_run/', include('Compile_run.urls')),
    url(r'^Leader/', include('Leader.urls')),
    url(r'^adminpanel/',include('adminpanel.urls')),
]

home/urls.py
from django.conf.urls import url,include
from . import views
app_name='home'
urlpatterns = [
    url(r'^$',views.contest,name='contest'),
    url(r'^(?P<contest_id>[0-9]+)/contest_details/$',views.contest_details,name='contest_details'),
    url(r'^(?P<contest_id>[0-9]+)/contest_info/$',views.contest_info,name='contest_info'),
    #url(r'^problem/(?P<problem_id>[0-9]+)/$',views.problem,name='problem'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^onsearch/$',views.onsearch,name='onsearch'),
    url(r'^profile/$',views.profile,name='profile'),
    url(r'^profileupdate/$',views.profileUpdate,name='profileUpdate'),
    url(r'^(?P<contest_id>[0-9]+)/contest_signup/$',views.contest_signup,name='contest_signup'),
    url(r'^contact_us/$',views.contactPage,name='contactPage'),
    url(r'^contact/$',views.contact,name='contact'),
]

adminpanel/models.py
from django.db import models

# Create your models here.

adminpanel/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from django.template import loader
from home.models import Contest,Problem
from Compile_run.models import TestCase
from django.http import Http404
from django.contrib.auth import authenticate,login
from Compile_run.models import Problem_session
from login.models import User,AdminUser
from Compile_run.views import getWelO
from home.views import get_u

def index(request):
	get_object_or_404(AdminUser,user=get_object_or_404(User,username=get_u(request)))
	data=Contest.objects.all();
	return render(request,'adminpanel/addqus.html',{'data':data})
def details(request):
	return render(request,'adminpanel/details.html')

def addcon(request):
	if request.method=='POST':
		form=Contest(con_name=request.POST.get('name'),con_date=request.POST.get('start_time')[:10:],start_time=request.POST.get('start_time'),start=request.POST.get('start_time'),end_time=request.POST.get('end_time'),end=request.POST.get('end_time'),org_name=request.POST.get('org_name'),image=request.POST.get('image'),tagline=request.POST.get('tagline'),disc=request.POST.get('disc'),rules=request.POST.get('rules'),prize=request.POST.get('prize'),scoring=request.POST.get('scoring'))
		form.save()
		data=Contest.objects.all();
		return render(request,'adminpanel/addqus.html',{'data':data})

def showqus(request,con_id):
	return render(request,'adminpanel/showqus.html',{'con_id':con_id})

def addqus(request):
	if request.method=='POST':
		con_id=request.POST.get('id')
		contest=Contest.objects.get(id=con_id)
		form=Problem(Contest=contest,p_name=request.POST.get('problem'),score=request.POST.get('marks'),p_level=request.POST.get('level'),p_disc=request.POST.get('disc'),p_input=request.POST.get('input'),p_cons=request.POST.get('cons'),p_output=request.POST.get('output'),sample_input=getWelO(request.POST.get('sample_input')),sample_output=getWelO(request.POST.get('sample_output')),exp=request.POST.get('exp'))
		form.save()
		data=Contest.objects.all();
		return render(request,'adminpanel/addqus.html',{'data':data})

def allqus(request,con_id):
	if request.method=='POST':
		try:
			data=Problem.objects.filter(Contest=Contest.objects.get(id=con_id))
			print (data)
		except Problem.DoesNotExist:
			raise Http404("Problems does not exits")
		return render(request,'adminpanel/allqus.html',{'data':data})

def addtest(request,p_id):
	return render(request,'adminpanel/addtest.html',{'problem':Problem.objects.get(id=p_id)})

def savetest(request,p_id):
	test_input = ""
	test_output = ""
	if request.POST.get('inputeditor') == 'on':
		test_input = getWelO(request.POST.get('input'))
	elif request.POST.get('inputupload') == 'on':
		ifile = open(request.POST.get('inputfile'))
		test_input = getWelO(ifile.read())

	if request.POST.get('outputeditor') == 'on':
		test_output = getWelO(request.POST.get('output'))
	elif request.POST.get('outputupload') == 'on':
		ifile = open(request.POST.get('outputfile'))
		test_input = getWelO(ifile.read())

	problem=Problem.objects.get(id=p_id)
	tc=TestCase(Problem=problem,testin=test_input,testout=test_output,weight=request.POST.get('weight'))
	tc.save()
	return render(request,'adminpanel/addtest.html',{'problem':Problem.objects.get(id=p_id)})

def addsession(request,p_id):
	return render(request,'adminpanel/addsession.html',{'problem':Problem.objects.get(id=p_id)})

def savesession(request,p_id):
	if request.method == 'POST':
		problem = Problem.objects.get(id=p_id)
		if Problem_session.objects.filter(Problem=problem).first() is None:
			p_ses = Problem_session(Problem=problem,c_session_code=request.POST.get('c'),cpp_session_code=request.POST.get('cpp'),java_session_code=request.POST.get('java'),py_session_code=request.POST.get('python'))
			p_ses.save()
		else:
			p_ses = Problem_session.objects.get(Problem=problem)
			p_ses.c_session_code = request.POST.get('c')
			p_ses.cpp_session_code = request.POST.get('cpp')
			p_ses.java_session_code = request.POST.get('java')
			p_ses.py_session_code = request.POST.get('python')
			p_ses.py_session_code = request.POST.get('python3')
			p_ses.save()
		data=Contest.objects.all();
		return render(request,'adminpanel/addqus.html',{'data':data})


def editproblem(request,p_id):
	problem = Problem.objects.get(id=p_id)
	con_id = problem.Contest.id
	return render(request,'adminpanel/showqus.html',{'con_id':con_id,'problem':problem,'editmode':True})

def editqus(request,p_id):
	problem = Problem.objects.get(id=p_id)
	problem.p_name=request.POST.get('problem')
	problem.score=request.POST.get('marks')
	problem.p_level=request.POST.get('level')
	problem.p_disc=request.POST.get('disc')
	problem.p_input=request.POST.get('input')
	problem.p_cons=request.POST.get('cons')
	problem.p_output=request.POST.get('output')
	problem.sample_input=getWelO(request.POST.get('sample_input'))
	problem.sample_output=getWelO(request.POST.get('sample_output'))
	problem.exp=request.POST.get('exp')
	problem.save()
	return render(request,'adminpanel/allqus.html',{'data':Problem.objects.filter(Contest=Contest.objects.get(id=problem.Contest.id))})

adminpanel/templates/adminpanel/addqus.html
{% load staticfiles %}

{% if error_message %}
  <p><strong>{{ error_message }}</strong></p>
{% endif %}

  <link rel="stylesheet" type="text/css" href="{% static 'adminpanel/style.css' %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootnotestrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>

<div class="container">

<center><h3 class="hed"><span class="glyphicon glyphicon-list"></span>&nbsp;YOUR ACTIVE CONTESTS<span class="glyphicon glyphicon-task"></span></h3><a href="{% url 'adminpanel:details' %}">+Add New Contest</a></center>
<br>
{% for con in data %}
<form action="{% url 'adminpanel:showqus' con.id %}" method="post">
{% csrf_token %}

<div class="row">

     <div class="col-sm-2">
    <strong>{{ con.id }}-{{ con.con_name }}</strong>
    </div>
    <div class="col-sm-1">
    <strong>{{ con.con_date }}</strong>
    </div>
    <div class="col-sm-2">
    <strong>{{ con.start_time }}</strong>
    </div>
    <div class="col-sm-2">
    <strong>{{ con.end_time }}</strong>
    </div>
    <div class="col-sm-2">
    <strong><button class="btn btn-primary" name="submit">ADD CHALLENGE</button></strong>
    </div>

</form>
<form action="{% url 'adminpanel:allqus' con.id %}" method="post">
{% csrf_token %}
    <div class="col-sm-2">
    <strong><button class="btn btn-success" name="submit">SHOW CHALLENGS</button></strong>
</div>
    <div class="col-sm-1">
 <a href="{% url 'Leader:index' con.id %}">@confirm Leaderboard</a>
</div>
</form>
</div>
<br>
{% endfor %}
</div>

adminpanel/templates/adminpanel/addsession.html
{% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'adminpanel/style.css' %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>

				<div class="container">
				<hr><strong>Problem Name : {{ problem.p_name }} </strong><hr><strong>Contest Name : {{ problem.Contest.con_name }} </strong>
				<hr>
				<strong>Problem Statement :<br> {{ problem.p_disc }} </strong>
				<hr>

				<form action="{%  url 'adminpanel:savesession' problem.id %}" method="post">
				{% csrf_token %}
      			<div class="form-group">
			  	<label for ="description"> C Session Code :</label>
			  	<textarea  class="form-control" id="description" name="c" placeholder="sample code" rows="10" required></textarea>
				</div>
				<div class="form-group">
			  	<label for ="description"> Cpp Session Code :</label>
			  	<textarea  class="form-control" id="description" name="cpp" placeholder="sample code" rows="10" required></textarea>
				</div>
				<div class="form-group">
			  	<label for ="description"> Java Session Code :</label>
			  	<textarea  class="form-control" id="description" name="java" placeholder="sample code" rows="10" required></textarea>
				</div>
				<div class="form-group">
			  	<label for ="description"> Python Session Code :</label>
			  	<textarea  class="form-control" id="description" name="python" placeholder="sample code" rows="10" required></textarea>
				</div>
				<div class="form-group">
			  	<label for ="description"> Python3 Session Code :</label>
			  	<textarea  class="form-control" id="description" name="python3" placeholder="sample code" rows="10" required></textarea>
				</div>
				<button type="submit" href="" class="btn btn-default">Add Sessions</button>
				</form>
				</div>

adminpanel/templates/adminpanel/addtest.html
{% load staticfiles %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
  <script>
  function setname(id){
      if(id=='inputupload'){
          document.getElementById('input').innerHTML = '<input type="file" name="inputfile" accept="text/plain" required>';
          document.getElementById('inputeditor').checked=false;
      }
      else if(id == 'inputeditor'){
          document.getElementById('input').innerHTML = '<textarea  class="form-control" id="description" name="input" placeholder="input" rows="10" required></textarea>';
          document.getElementById('inputupload').checked=false;
      }
      else if(id == 'outputeditor'){
        document.getElementById('output').innerHTML = '<textarea  class="form-control" id="description" name="output" placeholder="input" rows="10" required></textarea>';
        document.getElementById('outputupload').checked=false;
      }
      else {
        document.getElementById('output').innerHTML = '<input type="file" name="outputfile" accept="text/plain" required>';
        document.getElementById('outputeditor').checked=false;
      }
  }
  </script>
  <div class="container">
				<hr>
        <hr><strong>Problem Name : {{ problem.p_name }} </strong><hr><strong>Contest Name : {{ problem.Contest.con_name }} </strong>
				<strong>Problem Statement :<br> {{ problem.p_disc }} </strong>
				<hr>
		  <form action="{%  url 'adminpanel:savetest' problem.id %}" method="post">
				{% csrf_token %}
      	<div class="form-group">
			  	<label for ="description"> Input Format:</label>
          editor <input type="radio" id="inputeditor" name="inputeditor" onclick="setname('inputeditor')">
          upload <input type="radio" id="inputupload" name="inputupload" onclick="setname('inputupload')">
          <div id="input">
			    </div>
        </div>
				<div class="form-group">
			  	<label for ="description">Output format:</label>
          editor <input type="radio" id="outputeditor" name="outputeditor" onclick="setname('outputeditor')">
          upload <input type="radio" id="outputupload" name="outputupload" onclick="setname('outputupload')">
          <div id="output">
          </div>
			    </div>
				<div class="form-group">
			  	<label for ="description">weightage:</label>
			  	<input type="number" class="form-control" id="description" name="weight" placeholder="Enter Your weight" rows="10"/>
				</div>

				<button type="submit" href="" class="btn btn-default">ADD TEST CASE</button>
			</form>
</div>

adminpanel/templates/adminpanel/allqus.html
{% for i in data %}
	{{ i }}
 &nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'adminpanel:addtest' i.id %}">add testcases</a> &nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'adminpanel:addsession' i.id %}">add session</a> &nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'adminpanel:editproblem' i.id %}">edit problem</a>
<hr>
{% endfor %}

adminpanel/templates/adminpanel/details.html

{% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'adminpanel/style.css' %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.js' %}" charset="UTF-8"></script>
<script type="text/javascript" src="{% static 'js/locales/bootstrap-datetimepicker.fr.js' %}" charset="UTF-8"></script>

<link href="{% static 'css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
<script type="text/javascript">
    $('.form_datetime').datetimepicker({
        //language:  'fr',
        weekStart: 1,
        todayBtn:  1,
		autoclose: 1,
		todayHighlight: 1,
		startView: 2,
		forceParse: 0,
        showMeridian: 1
    });

</script>

<div class="container" style="background:url("coding.jpg");">

<div class="col-sm-2"></div>
<div class="col-sm-8">
  <form action="{% url 'adminpanel:addcon' %}" method="post">
  {% csrf_token %}
  	<div class="hed">
<h3>ENTER THE BASICS OF YOUR CONTEST</h3>
</div>
<br>
<br>
	   <div class="form-group">
			  <label for="name">Context name:</label>
			  <input type="text" class="form-control" id="name" name="name" placeholder=" Enter Name">
		</div>
		<div class="form-group">
			  <label for="name">Start Time:</label>
			  <input type="text" class="form-control form_datetime" id="name" name="start_time" placeholder=" HH:MM:SS">
			  <script type="text/javascript">
		    $(".form_datetime").datetimepicker({format: 'yyyy-mm-dd hh:ii'});
		</script>
		</div>


		<div class="form-group">
			  <label for="name">End Time:</label>
			  <input type="text" class="form-control form_datetime" id="name" name="end_time" placeholder=" HH:MM:SS">
			  <script type="text/javascript">
		    $(".form_datetime").datetimepicker({format: 'yyyy-mm-dd hh:ii'});
		</script>
		</div>
		<div class="form-group">
			  <label for="name">Organisation Name:</label>
			  <input type="text" class="form-control" id="name" name="org_name" placeholder=" Enter Name">

		</div>
<br>
<br>
		<div class="hed">
<h3>ENTER THE DETAILS OF YOUR CONTEST</h3>
</div>
<br>
<br>
		<div class="form-group">
			  <label for="name">Backgroung image::</label>
			  <input type="file" class="form-control btn-primary" id="name" name="image" placeholder=" Enter Name">
		</div>
		<div class="form-group">
			  <label for="name">Context Tagline:</label>
			  <input type="text" class="form-control" id="name" name="tagline" placeholder=" Enter Name">
		</div>
		<div class="form-group">
			  	<label for ="description"> Discription:</label>
			  	<textarea  class="form-control" id="description" name="disc" placeholder="Enter Your Message" rows="10"></textarea>
		</div>
		<div class="form-group">
			  	<label for ="description">Rules:</label>
			  	<textarea  class="form-control" id="description" name="rules" placeholder="Enter Your Message" rows="10"></textarea>
		</div>
		<div class="form-group">
			  	<label for ="description">Prizes:</label>
			  	<textarea  class="form-control" id="description" name="prize" placeholder="Enter Your Message" rows="10"></textarea>
		</div>
		<div class="form-group">
			  	<label for ="description">Scoring:</label>
			  	<textarea  class="form-control" id="description" name="scoring" placeholder="Enter Your Message" rows="10"></textarea>
		</div>

			  	<button type="submit" class="btn btn-primary" class="btn btn-default">SUBMIT</button>

	</form>
</div>
<div class="col-sm-2"></div>

</div>

adminpanel/templates/adminpanel/index.html
<h3>yo</h3>

adminpanel/templates/adminpanel/showqus.html
{{ con_id }}

{% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'adminpanel/style.css' %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-lg-offset-2 col-md-10 col-md-offset-1 col-sm-10">


  			<ul class="nav nav-tabs">
   			 <li class="active"><a data-toggle="tab" href="#home"><span class="glyphicon glyphicon-home"></span>&nbsp;PROBLEM SET</a></li>

  			</ul>
  			<br>
  			<br>
  			<div class="tab-content">
   		 		<div id="home" class="tab-pane fade in active">

<div class="col-sm-12">
  {% if editmode %}
  <form action="{% url 'adminpanel:editqus' problem.id %}" method="post">
  {% else %}
  <form action="{% url 'adminpanel:addqus' %}" method="post">
  {% endif %}
  {% csrf_token %}
  	<div class="hed">
<h4>DETAILS OF PROBLEM</h4>
</div>
<br>
<br>
		<div class="form-group">
			  <label for="name">Contest ID:</label>
			  <input type="text" class="form-control" id="name" name="id" placeholder="{{ con_id }}" value="{{ con_id }}">
		</div>
		<div class="form-group">
			  	<label for ="description">Problem:</label>
			  	<input type="text" class="form-control" id="description" name="problem" placeholder="problem name without spaces" required value="{{ problem.p_name }}">
		</div>
		<div class="form-group">
			  <label for="name">Marks:</label>
			  <input type="text" class="form-control" id="name" name="marks" placeholder=" marks" required value="{{ problem.score }}">
		</div>
		<div class="form-group">
			  <label for="name">Level:</label>
			  <input type="text" class="form-control" id="name" name="level" placeholder=" easy/mediam/hard" required  value="{{ problem.p_level }}">
		</div>
		<div class="form-group">
			  	<label for ="description"> Discription:</label>
			  	<textarea  class="form-control" id="description" name="disc" placeholder="Enter Your Message" rows="15" required>{{ problem.p_disc }}</textarea>
		</div>
		<div class="form-group">
			  	<label for ="description">Constraints:</label>
			  	<textarea  class="form-control" id="description" name="cons" placeholder="Enter Your Message" rows="10" required>{{ problem.p_cons }}</textarea>
		</div>
		<div class="form-group">
			  	<label for ="description"> Input Format:</label>
			  	<textarea  class="form-control" id="description" name="input" placeholder="Enter Your Message" rows="10" required>{{ problem.p_input }}</textarea>
		</div>

		<div class="form-group">
			  	<label for ="description">Output format:</label>
			  	<textarea  class="form-control" id="description" name="output" placeholder="Enter Your Message" rows="10" required>{{ problem.p_output }}</textarea>
		</div>

		<div class="form-group">
			  	<label for ="description"> Sample Input:</label>
		</div>
    <textarea  class="form-control" id="description" name="sample_input" placeholder="Enter Your Message" rows="10" required>{{ problem.sample_input }}</textarea>
		<div class="form-group">
			  	<label for ="description"> Sample Output:</label>
			  	<textarea  class="form-control" id="description" name="sample_output" placeholder="Enter Your Message" rows="10" required>{{ problem.sample_output }}</textarea>
		</div>

		<div class="form-group">
			  	<label for ="description"> Explanations : </label>
			  	<textarea  class="form-control" id="description" name="exp" placeholder="Enter Your Message" rows="10" required>{{ problem.exp }}</textarea>
		</div>

			  	{% if editmode %}
          <button type="submit" class="btn btn-primary" class="btn btn-default">Save Changes</button>
          {% else %}
          <button type="submit" class="btn btn-primary" class="btn btn-default">ADD</button>
          {% endif %}
	</form>
</div>
				</div>

	      </div>
	     </div>
	   </div>





















  </div>



</div>
</div>


    <hr>